/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,vue,ts}',
    './components/*.{js,vue,ts}',
    './layouts/*.vue',
    './pages/*.vue',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['"DM Sans"', 'sans-serif'],
        colgate: ['"Colgate Bold"'],
      },
      fontWeight: {
        light: 300,
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      fontSize: {
        h1: '50px',
        h2: '40px',
        h3: '28px',
        h4: '22px',
        'h4-mobile': '17px',
        xl: '22px',
        large: '18px',
        regular: '16px',
        small: '14px',
        disclaimer: '13px',
        mini: '12px',
        'label-sm': '11px',
      },
      lineHeight: {
        xxs: '18px',
        xs: '20px',
        sm: '22px',
        tiny: '24px',
        body: '26px',
        base: '28px',
        lg: '30px',
        xl: '32px',
        '2xl': '36px',
        '3xl': '46px',
        '4xl': '70px',
      },
      colors: {
        colgate: '#F50005',
        white: '#FFFFFF',
        charcoal: '#595655',
        brick: '#8F1F1D',
        monza: '#D6090C',
        alabaster: '#F9F9F9',
        seashell: '#F1F1F1',
        titan: '#EEEEEE',
        gallery: '#777574',
        valerie: '#FEE5E6',
        ruby: '#D6090C',
        'light-gray': '#EAEAEA',
        'charcoal-light-rgba': 'rgba(89, 86, 85, 0.1)',
        'charcoal-dark-rgba': 'rgba(89, 86, 85, 0.8)',
        'white-dark-rgba': 'rgba(255, 255, 255, 0.9)',
        'white-light-rgba': 'rgba(255, 255, 255, 0.1)',
      },
      screens: {
        xl: '1148px',
        'md-max': '767px',
        'quiz-nav': '1326px',
      },
    },
  },
  plugins: [],
}
